### ISSUE TITLE
Value with special Charachter returns sqlite error

### ISSUE THREAD

**Issue by mahaben** [jchristn/SqliteWrapper#1]
Hello,

I'm facing a problem when I try to insert a row with a value 'pièces'. I got sqlite error near 'pièces', syntax error.

Can you help please?

Thanks

**Comment by jchristn** [comment]
Hi!  Could you enable debug when instantiating the DatabaseClient and send me the console output?  I'd like to make sure the query builder for INSERT is properly prepending N to the query, i.e.
INSERT INTO ... <cols>, VALUES (N'pièces')

**Comment by jchristn** [comment]
No need to test this @mahaben - I found the issue.  The querybuilder is incorrectly treating the accented characters as Unicode.  I will have a patch today.  Thanks!

**Comment by jchristn** [comment]
Hi @mahaben I just committed https://github.com/jchristn/SqliteWrapper/commit/f98eb0b0387e505f7fd46a2b8944d229565f7f69 and published an update to NuGet (v1.0.5).  It may take a few minutes to appear in NuGet, but when it does, can you give it a test and see if it works for you?  Please re-open this if there is any issue.  Thanks!
