### ISSUE TITLE
Update package for .NET Core 3?

### ISSUE THREAD

**Issue by ravensorb** [jchristn/SqliteWrapper#2]
Any thoughts to adding support for .NET core 3?

**Comment by jchristn** [comment]
Hi @ravensorb it should work fine with .NET core 3 projects.  Have you tested it?  Cheers

**Comment by jchristn** [comment]
I just tested on .NET Core 3 and .NET Core 3.1, both worked great.  Please let me know if any issues.
![image](https://user-images.githubusercontent.com/1421081/74178949-4ed4ec80-4bf1-11ea-80f2-7c14c484ca6d.png)

**Comment by ravensorb** [comment]
I think I had an issue with the project -- I was trying in a linux system.  All seem to be good now.

Thanks!

> I just tested on .NET Core 3 and .NET Core 3.1, both worked great. Please let me know if any issues.
> ![image](https://user-images.githubusercontent.com/1421081/74178949-4ed4ec80-4bf1-11ea-80f2-7c14c484ca6d.png)

**Comment by jchristn** [comment]
Oh nice!  Ya know, I probably should not have closed so quickly, and should have solicited feedback on your environment :)  Thanks for getting back to me.  Let me know if any other issues arise or if you have any other feedback!  Thanks!

**Comment by ravensorb** [comment]
No worries :) Right now I am running into an issue with the query method as I am getting an error loading on of the System.Data.Sqlite assemblies.  Trying to figure out if its my env (Mint with .netcore 3.1) or something else.  Right now I have done a fork of your library and am trying a few things.  I'll keep you posted.

**Comment by jchristn** [comment]
Awesome, opening this back up since the issue could be related to a lack of support for core 3.  Cheers!

**Comment by jchristn** [comment]
Hi @ravensorb wanted to see if you had any update on your side or anything with which I can help?

**Comment by ravensorb** [comment]
I am still tracking thing down.  What I have done so far is swapped System.Data.Sqlite for Microsoft.Data.Sqlite and it worked. However I am not convinced that the issue is with System.Data.Sqlite yet.  My use case was to leverage your library in PowerShell and in Cakebuild.net - cakebuild was where I hit the issue and the only fix was moving to the other sqlite library.  I am trying powershell and straight .netcore next (planning on spending some time this weekend).

**Comment by jchristn** [comment]
Hi @ravensorb are you still having any issues or is it safe to close this?
