### ISSUE TITLE
Add "COLLATE NOCASE" by adding Column.

### ISSUE THREAD

**Issue by hhu-mahmoud** [jchristn/SqliteWrapper#3]
I want to use the method create table and i want to add to column the attribute "**COLLATE NOCASE**", but there is no option to do that, so i must use the normal string query in this case.

**Comment by jchristn** [comment]
Hi @hhu-mahmoud thanks for this, I added ```COLLATE NOCASE``` by default on ```TEXT``` fields.  I don't want to make this a configurable option (complexity) and doing this gives it parity with SQL Server, MySQL, and others (case-insensitive text matching during SELECT).

Commit: https://github.com/jchristn/SqliteHelper/commit/d387251442fb974c085276c2852c05ecad2cdb22
NuGet: https://www.nuget.org/packages/SqliteHelper/1.1.5

Thanks!

**Comment by hhu-mahmoud** [comment]
@jchristn  Thank you :)
